Feat/project setup
postech-soat-study-group/tech-challenge-api pull request #1
Opened 2024-05-07 21:55 UTC by r4ulmanzas

## Description
[Setup project structure](https://www.notion.so/Criar-estrutura-do-Projeto-5bd60908a6cc40a881f39bdd51b24f2e)

This PR provides the very base project configuration. Summary:
- Creates the domain model project completely segregated from infrastructure (such as spring);
- Adds a multi-stage dockerfile that runs with a non-root user;
- Adds swagger configuration, that right now is empty because there are no endpoints;
- Adds the simplest health check possible using Spring Actuator.

I also added some repository configuration such as pull request templates and code owners file.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How Has This Been Tested?

Swagger configuration evidence:
![image](https://github.com/postech-soat-study-group/tech-challenge-api/assets/158320898/21190f62-c2a2-4b3a-a9d5-88a1305ccbe2)

Health check evidence:
![image](https://github.com/postech-soat-study-group/tech-challenge-api/assets/158320898/56bccdff-3358-4ff4-8dcf-d2175d1f260e)

To verify that the docker setup is working as expected, all you need to do is run the project using docker compose right from you machine!

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2024-05-07 22:12 UTC, andreoliveiramorais requested changes
LGTM, só a questão das pastas que estão vindo no PR. Resto ta legal.

2024-05-07 22:12 UTC, andreoliveiramorais commented on .idea/.gitignore
@r4ulmanzas acho que essa pasta pode sumir, certo?

2024-05-08 01:20 UTC, felipetomm reviewed
Só a questão do @andreoliveiramorais pra validar. Deixei meus 5 cents ali.

2024-05-08 01:20 UTC, felipetomm commented on .idea/.gitignore
Bacana tua obs @andreoliveiramorais . 
Eu acho que como é da ide que vamos usar, da pra manter ela, até porque dentro tem todas as configs pra rodar o projeto.. A não ser que ela fique sofrendo alterações a todo momento pelo uso de cada um de nós, ai acho que seria bacana a gente rever. Digo isso por não conhecer muito ainda da estrutura do java e do comportamento da IDE. No vscode acabamos sempre subindo junto o diretório com as configs do projeto pra rodar nele.

2024-05-08 13:17 UTC, gspaiva approved these changes
Só precisamos remover a pasta do .idea e podemos fazer o merge. Já estou aprovando antes para não precisar de approve novamente.

2024-05-08 13:17 UTC, gspaiva commented on .idea/.gitignore
@felipetomm Talvez possa dar algum problema de compatibilidade ao subir essa pasta, no intellij, tem alguns arquivos de configuração de projeto que pode ser feito, mas esse arquivo não fica na .idea não.
Exemplo: https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

2024-05-08 13:17 UTC, gspaiva commented on Dockerfile
> +FROM amazoncorretto:21-alpine-jdk
Talvez eu adicione um novo arquivo Dockerfile-mac, que tem algumas diferenças nas imagens. Só comentei pra não esquecer.

2024-05-08 13:35 UTC, r4ulmanzas commented on .idea/.gitignore
O @felipetomm acertou em cheio! Dentro da pasta `.idea existem arquivos que podem ser versionados, e outros que não devem. 

Os arquivos que podem ser versionados são de configurações básicas de execução, e basicamente garantem que todos estão rodando o projeto da mesma forma localmente. Remover esses arquivos não é nada grave, pois o intellij consegue reconstruir todos eles - com alguma diferença em cada máquina - e, como estamos buildando o projeto dentro do Dockerfile, no fim das contas é a versão do docker que importa.

Os arquivos que não podem ser versionados são aqueles que guardam configurações que revelam informações sobre a máquina host. Por exemplo, configurações que indiquem a pasta e o usuário com os quais rodei o projeto na minha máquina. Por não serem versionáveis, o próprio intellij adiciona esse `.gitignore` dentro da pasta `.idea`.

Obs @gspaiva: esse exemplo é de style guide, e não configuração de build/execução.

2024-05-08 13:37 UTC, r4ulmanzas commented on .idea/.gitignore
Dito isso, vou tacar fogo na `.idea` para desbloquear o PR e permitir que vocês sigam no desenvolvimento, pois não estou em condições de saúde para ser mais participativo =(

2024-05-08 14:04 UTC, felipetomm approved these changes

2024-05-09 20:53 UTC, andreoliveiramorais approved these changes

2024-05-09 20:53 UTC, merged