feat: initial fake checkout implementation
postech-soat-study-group/tech-challenge-api pull request #15
Opened 2024-05-26 20:24 UTC by felipetomm

## Description
[Notion card](https://www.notion.so/)
Implements initial structure to the fakeCheckout.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Not tested yet. I had only ran locally and verified that services are running ok.

There are 2 warnings about method and class never used.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-26 20:27 UTC, felipetomm commented on infrastructure/src/main/java/postech/soat/tech/challenge/external/api/checkout/services/FakeCheckoutOrder.java
> +public interface FakeCheckoutOrder {
Fiquei um pouco perdido de onde iria essa interface. Acredito que deva ficar na `application`, junto com as outras interfaces de `repository`. Consequentemente, fiquei na dúvida de onde deve ser realizada a injeção dessa interface. Como depende ainda da implementação de `Order`, deixei esses dois pontos acima em aberto.

2024-05-26 23:16 UTC, r4ulmanzas approved these changes

2024-05-26 23:35 UTC, andreoliveiramorais requested changes

2024-05-26 23:35 UTC, andreoliveiramorais commented on infrastructure/src/main/java/postech/soat/tech/challenge/external/api/checkout/services/FakeCheckoutOrder.java
> +public interface FakeCheckoutOrder {
O que eu faria era ter uma abstração para CheckoutOrder, que estaria tanto na `application ` (com os use cases e as interfaces repositories) como no `domain ` (com as regras especificas).
Aqui sim poderiamos ter o adapter com a implementação de um fakecheckout. Assim, conseguiriamos criar uma nova regra verdadeira mexendo apenas na infraestructure (ou seja, nos adapters). Faz sentido?

2024-05-27 00:29 UTC, felipetomm commented on infrastructure/src/main/java/postech/soat/tech/challenge/external/api/checkout/services/FakeCheckoutOrder.java
> +public interface FakeCheckoutOrder {
Não sei se entendi bem, mas eu até tinha pensado inicialmente em ter algo semelhante a uma `factory` pra gerenciar os pagamentos. Sendo que o fluxo para pagar pode ser o mesmo. Só não segui nessa linha pois achei que ficou muito superficial a descrição desse item no trabalho, e ai fiquei com um pouco de receio de botar muita coisa agora.

Nesse caso da factory que comentei, poderia ter N serviços de pagamento, mas todos seguindo sempre o mesmo fluxo, ex: gerar um qr-code, receber um pagamento, etc..., e ai a factory que decide pra qual serviço vai.

2024-05-28 22:08 UTC, closed without merging